version: '3.3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    command: gunicorn brinquedoteca.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=brinquedoteca
      - MYSQL_PASSWORD=brinquedotecapwd
      - MYSQL_DATABASE=brinquedoteca_db
